# Generated by Django 6.0.7 on 2026-07-12 22:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("jobs", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="SkillTag",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("name", models.CharField(max_length=50, unique=True)),
                ("slug", models.SlugField(blank=True, unique=True)),
            ],
        ),
        migrations.AddField(
            model_name="job",
            name="raw_scraper_meta",
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name="job",
            name="salary_max",
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, max_length=12, null=True),
        ),
        migrations.AddField(
            model_name="job",
            name="salary_min",
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, max_length=12, null=True),
        ),
        migrations.AlterField(
            model_name="job",
            name="location",
            field=models.CharField(blank=True, default="Remote", max_length=255),
        ),
        migrations.AddField(
            model_name="job",
            name="tags",
            field=models.ManyToManyField(blank=True, related_name="listings", to="jobs.skilltag"),
        ),
    ]
